name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: docker-compose build
